package edu.uoregon.secondlook

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ResearcherSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                // Access control by convention.
//                accessControl()

//                if(actionName in ['list','show','index']){
//                    return true
                if ((controllerName+':'+actionName) in ['computerTranscript:submit']) {
                    return true
                } else {
                    accessControl(auth: false)
//                    accessControl()
                }
            }
        }
    }
}
