package edu.uoregon.secondlook

import grails.test.mixin.Mock
import grails.test.mixin.TestFor

/**
 * See the API for {@link grails.test.mixin.services.ServiceUnitTestMixin} for usage instructions
 */
@TestFor(TotalWordReadService)
@Mock([ComputerTranscription,Passage])
class TotalWordReadServiceTests {

    void testSomething() {
        File file = new File("test/test-data/531-2531/timings.all.txt")
//        println "${file.absolutePath}"
        Passage passage = new Passage(
                externalId: "1234"
                ,text: passageText2
        )
//        Transcription transcription = new Transcription(
//                fileName: "test1"
//                ,transcript: file.text
//                ,passage: passage
//                ,audioData: new byte[0]
//        )
//        passage.addToTranscriptions(transcription)
//        Integer totalWordsRead = service.calculateTotalWordsRead(transcription)

        String transcript = file.text
        assert 3463==transcript.size()
        println "transcript size ${transcript.size()}"
        String outputText = passage.text
//        outputText = outputText.replaceAll("\\n","")
        outputText = outputText.replaceAll("\\s{2,}"," ")

//        outputText = outputText.replaceAll(" "," _ ")
        println "passageText ${outputText}"
        Integer totalWordsRead = TWR.findTWR(outputText,transcript)
        assert totalWordsRead==119
        println "twr ${totalWordsRead}"
    }



    String passageText="YOU ARE STANDING ON A SANDY WHITE BEACH ON THE GULF OF MEXICO LOOKING OUT OVER THE WATER YOU NOTICE A HUGE BIRD WITH LONG NARROW WINGS GLIDING OVER THE OCEAN SUDDENLY THE BIRD TUCKS ITS WINGS TO ITS SIDE AND DROPS A HUNDRED FEET STRAIGHT DOWN INTO THE WATER BEFORE YOU CAN BLINK IT SHOOTS OUT OF THE SEA WITH A LARGE FISH IN ITS CLAWS AND SOARS UPWARD INTO THE SKY YOU HAVE JUST SEEN AN OSPREY CATCH ITS BREAKFAST UNFORTUNATELY THE SIGHT YOU HAVE JUST SEEN HAS BECOME QUITE RARE THERE ARE FAR FEWER OSPREYS TODAY THAN THERE ONCE WERE ONE REASON FOR THIS DECLINE IS THAT PEOPLE HAVE MOVED INTO PLACES THAT WERE ONCE OSPREY NESTING AREAS AS MORE AND MORE PEOPLE SETTLED IN THESE AREAS THEY CUT DOWN TREES TO BUILD HOUSES SHOPS AND BUILDINGS THE GRADUAL ENCROACH OF CIVILIZATION HAS LEFT OSPREYS WITH FEWER PLACES TO BUILD THEIR NESTS IN ADDITION PEOPLE BEGAN TO USE FERTILIZERS AND OTHER CHEMICALS THAT DRAINED INTO THE WATER SUPPLY THIS POISONED THE FISH THAT OSPREYS FEED ON FINALLY PEOPLE SOMETIMES FRIGHTENED THE OSPREYS AWAY FROM THEIR NESTS LEAVING THEIR EGGS TO BE DESTROYED BY THE HOT SUN FORTUNATELY HELP IS ON THE WAY MANY AREAS WHERE OSPREYS BUILD THEIR NESTS ARE NOW PROTECTED ONE OF THESE IS THE GULF ISLANDS NATIONAL SEASHORE A PARK THAT STRETCHES FOR MORE THAN ONE HUNDRED MILES ALONG THE GULF OF MEXICO OSPREY NESTS CAN BE FOUND ON ALMOST ALL OF THE ISLANDS IN THE PARK TO PROTECT THE BIRDS PEOPLE ARE NOT ALLOWED IN MANY PARTS OF THE PARK AS A RESULT THE NUMBER OF OSPREYS ON THE ISLANDS IS SLOWLY INCREASING ALSO MANY COMPANIES AND WILDLIFE CLUBS HAVE SET UP MAN MADE NESTING PLATFORMS IN PLACES WHERE OSPREYS LIVE THESE PROVIDE OSPREYS WITH SAFE STURDY NESTING SITES OUT OF THE REACH OF PEOPLE BECAUSE OF THE HARD WORK OF CONCERNED PEOPLE THINGS ARE LOOKING UP FOR OSPREYS SOON WATCHING AN OSPREY SWOOP OUT OF THE SKY TO CATCH ITS MORNING MEAL MIGHT NOT BE SUCH A RARE SIGHT AFTER ALL"
    String passageText2 = "YOU ARE STANDING ON A SANDY WHITE BEACH ON THE GULF OF MEXICO LOOKING OUT OVER THE WATER YOU NOTICE A \n" +
            "HUGE BIRD WITH LONG NARROW WINGS GLIDING OVER THE OCEAN SUDDENLY THE BIRD TUCKS ITS WINGS TO ITS SIDE AND DROP\n" +
            "S A HUNDRED FEET STRAIGHT DOWN INTO THE WATER BEFORE YOU CAN BLINK IT SHOOTS OUT OF THE SEA WITH A LARGE FISH \n" +
            "IN ITS CLAWS AND SOARS UPWARD INTO THE SKY YOU HAVE   JUST SEEN AN OSPREY CATCH ITS BREAKFAST UNFORTUNATELY TH\n" +
            "E SIGHT YOU HAVE JUST SEEN HAS BECOME QUITE RARE THERE ARE FAR FEWER OSPREYS TODAY THAN THERE ONCE WERE ONE RE\n" +
            "ASON FOR THIS DECLINE IS THAT PEOPLE HAVE MOVED INTO PLACES THAT WERE ONCE OSPREY NESTING AREAS AS MORE AND MO\n" +
            "RE PEOPLE SETTLED IN THESE AREAS THEY CUT DOWN TREES TO BUILD HOUSES SHOPS AND BUILDINGS THE GRADUAL ENCROACH \n" +
            "OF CIVILIZATION HAS LEFT OSPREYS WITH FEWER PLACES TO BUILD THEIR NESTS IN ADDITION PEOPLE BEGAN TO USE FERTIL\n" +
            "IZERS AND OTHER CHEMICALS THAT DRAINED INTO THE WATER SUPPLY THIS POISONED THE FISH THAT OSPREYS FEED ON FINAL\n" +
            "LY PEOPLE SOMETIMES FRIGHTENED THE OSPREYS AWAY FROM THEIR NESTS LEAVING THEIR EGGS TO BE DESTROYED BY THE HOT\n" +
            " SUN FORTUNATELY HELP IS ON THE WAY MANY AREAS WHERE OSPREYS BUILD THEIR NESTS ARE NOW PROTECTED ONE OF THESE \n" +
            "IS THE GULF ISLANDS NATIONAL SEASHORE A PARK THAT STRETCHES FOR MORE THAN ONE HUNDRED MILES ALONG THE GULF OF \n" +
            "MEXICO OSPREY NESTS CAN BE FOUND ON ALMOST ALL OF THE ISLANDS IN THE PARK TO PROTECT THE BIRDS PEOPLE ARE NOT \n" +
            "ALLOWED IN MANY PARTS OF THE PARK AS A RESULT THE NUMBER OF OSPREYS ON THE ISLANDS IS SLOWLY INCREASING ALSO M\n" +
            "ANY COMPANIES AND WILDLIFE CLUBS HAVE SET UP MAN MADE NESTING PLATFORMS IN PLACES WHERE OSPREYS LIVE THESE PRO\n" +
            "VIDE OSPREYS WITH SAFE STURDY NESTING SITES OUT OF THE REACH OF PEOPLE BECAUSE OF THE HARD WORK OF CONCERNED P\n" +
            "EOPLE THINGS ARE LOOKING UP FOR OSPREYS SOON WATCHING AN OSPREY SWOOP OUT OF THE SKY TO CATCH ITS MORNING MEAL\n" +
            " MIGHT NOT BE SUCH A RARE SIGHT AFTER ALL"
}
